# Random Forest Regression

In [13]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('tourism_data_500_points.csv')
df

,Date,Location,Number_of_Visitors
0,2019-01-01 00:00:00.000000000,Kimberley Museum,3970
1,2019-01-01 00:00:00.000000000,McGregor Museum,4278
2,2019-01-01 00:00:00.000000000,William Humphreys Art Gallery,4354
3,2019-01-01 00:00:00.000000000,Magersfontein Battlefield,5956
4,2019-01-01 00:00:00.000000000,Ghost Tours & Historical Walks,5450
...,...,...,...
2495,2023-01-01 00:00:00.000000000,Kimberley Museum,3405
2496,2023-01-01 00:00:00.000000000,McGregor Museum,5090
2497,2023-01-01 00:00:00.000000000,William Humphreys Art Gallery,4292
2498,2023-01-01 00:00:00.000000000,Magersfontein Battlefield,5294
2499,2023-01-01 00:00:00.000000000,Ghost Tours & Historical Walks,1135

In [3]:
df.isnull().sum()

Date                  0
Location              0
Number_of_Visitors    0
dtype: int64

In [4]:
df['Location'].unique()

array(['Kimberley Museum', 'McGregor Museum',
       'William Humphreys Art Gallery', 'Magersfontein Battlefield',
       'Ghost Tours & Historical Walks'], dtype=object)

In [5]:
col = ['Location', 'Date']

In [6]:
df_encoder = pd.get_dummies(df, columns = col)
df_encoder

,Number_of_Visitors,Location_Ghost Tours & Historical Walks,Location_Kimberley Museum,Location_Magersfontein Battlefield,Location_McGregor Museum,Location_William Humphreys Art Gallery,Date_2019-01-01 00:00:00.000000000,Date_2019-01-03 22:16:06.733466933,Date_2019-01-06 20:32:13.466933867,Date_2019-01-09 18:48:20.200400801,...,Date_2022-12-05 15:34:59.398797600,Date_2022-12-08 13:51:06.132264528,Date_2022-12-11 12:07:12.865731472,Date_2022-12-14 10:23:19.599198400,Date_2022-12-17 08:39:26.332665328,Date_2022-12-20 06:55:33.066132272,Date_2022-12-23 05:11:39.799599200,Date_2022-12-26 03:27:46.533066128,Date_2022-12-29 01:43:53.266533072,Date_2023-01-01 00:00:00.000000000
0,3970,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,4278,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,4354,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,5956,False,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,5450,True,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,3405,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2496,5090,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2497,4292,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2498,5294,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2499,1135,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [7]:
X = df_encoder.drop('Number_of_Visitors', axis = 1)
y = df_encoder['Number_of_Visitors']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
model = RandomForestRegressor()

In [15]:
model.fit(X_train, y_train)

RandomForestRegressor()

In [16]:
y_pred = model.predict(X_test)

In [17]:
r2_score = metrics.r2_score(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
mae = metrics.mean_absolute_error(y_test, y_pred)

In [18]:
print("R2 Score: ", r2_score)
print("MSE: ", mse)
print("MAE: ", mae)

R2 Score:  -0.24038533665869166
MSE:  2781922.9552342
MAE:  1310.6983400000001

In [20]:
with open('results2.txt', 'w') as f:
    f.write(f"R2 score: {r2_score}\n")
    f.write(f"Mean Squared Error: {mse}\n")
    f.write(f"Mean Absolute Error: {mae}\n")